In [2]:
#   opencv python 코딩
#   얼굴을 인식한 상태에만 자동으로 촬영

import cv2
import datetime
from PIL import ImageFont, ImageDraw, Image
import numpy as np

()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
[[307 109  81  81]]
[[301 109  81  81]]
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
[[281 117  81  81]]
[[279 116  81  81]]
[[278 116  81  81]]
()
[[275 116  81  81]]
()
()
()
[[253 118 182 182]]
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
[[294 117  81  81]]
()
()
()
[[294 118  81  81]]
[[292 119  81  81]]
[[294 119  81  81]]
[[290 121  81  81]]
()
()
()
()
()
()
()
()
()
[[290 121  81  81]]
()
[[295 115  81  81]]
()
()
()
[[292 105  81  81]]
()
[[289 105  81  81]]
()
()
()
()
()
()
()
()
()
()
()
()
[[280 119  81  81]]
[[283 118  81  81]]
[[282 119  81  81]]
[[285 118  81  81]]
[[285 118  81  81]]
()
[[285 119  81  81]]
()
[[281 120  81  81]]
[[282 118  81  81]]
[[284 119  81  81]]
()
()
()
[[281 119  81  81]]
[[278 118  81  81]]
[[280 118  81  81]]
[[282 118  81  81]]
()
()
()
()
[[286 102  81  81]]
()
()
()
()
()
()
(

In [ ]:
# opencv python 코딩 기본 틀
# 카메라 영상을 받아올 객체 선언 및 설정(영상 소스, 해상도 설정)
capture = cv2.VideoCapture(0)
capture.set(cv2.CAP_PROP_FRAME_WIDTH, 640)
capture.set(cv2.CAP_PROP_FRAME_HEIGHT, 480)

In [ ]:
fourcc = cv2.VideoWriter_fourcc(*'XVID')    # 영상을 기록할 코덱 설정
font = ImageFont.truetype('fonts/ARIAL.TTF', 20) # 글꼴파일을 불러옴
is_record = False                           # 녹화상태는 처음엔 거짓으로 설정

In [ ]:
# haar cascade 검출기 객체 선언
face_cascade = cv2.CascadeClassifier('haarcascades/haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier('haarcascades/haarcascade_eye.xml')

In [ ]:
# 무한루프
while True:    
    now = datetime.datetime.now()
    nowDatetime = now.strftime('%Y-%m-%d %H:%M:%S')
    nowDatetime_path = now.strftime('%Y-%m-%d %H_%M_%S') # 파일이름으로는 :를 못쓰기 때문에 따로 만들어줌
    ret, frame = capture.read()     # 카메라로부터 현재 영상을 받아 frame에 저장, 잘 받았다면 ret가 참
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)  # 영상을 흑백으로 바꿔줌

    # scaleFactor를 1에 가깝게 해주면 정확도가 상승하나 시간이 오래걸림
    # minNeighbors를 높여주면 검출률이 상승하나 오탐지율도 상승
    faces = face_cascade.detectMultiScale(gray, scaleFactor= 1.5, minNeighbors=3, minSize=(20,20))
    eyes = eye_cascade.detectMultiScale(gray, scaleFactor= 1.5, minNeighbors=3, minSize=(10,10))
    print(faces)
    
    # 찾은 얼굴이 있으면
    # 얼굴 영역을 영상에 사각형으로 표시
    if len(faces) :
        for  x, y, w, h in faces :
            cv2.rectangle(frame, (x, y), (x + w, y + h), (255,255,255), 2, cv2.LINE_4)
            
    key = cv2.waitKey(30)   # 30ms 동안 키입력 대기
    if key == ord('r') and is_record == False:  # 현재 녹화상태가 아니며 r 키를 누르면
        is_record = True            # 녹화상태로 만들어줌
        # 비디오 객체에 (파일이름(한글가능), 인코더, 초당프레임률(정확하지 않음), 영상크기) 로 영상을 쓸 준비
        video = cv2.VideoWriter("capture/capture" + nowDatetime_path + ".avi", fourcc, 15, (frame.shape[1], frame.shape[0]))
    elif key == ord('r') and is_record == True: # 녹화중인 상태에서 다시 r키를 누르면
        is_record = False       # 녹화상태를 꺼줌
        video.release()         # 녹화 종료
    elif key == ord('c'):       # c 키를 누르면
        # (파일이름(한글불가, 영어만), 이미지)로 영상을 캡쳐하여 그림파일로 저장
        cv2.imwrite("capture/capture" + nowDatetime_path + ".png", frame)  # 파일이름(한글안됨), 이미지 
    elif key == ord('q'):  # 키보드의 q 를 누르면 무한루프가 멈춤
            break
    if is_record == True:       # 현재 녹화상태이면            
        # 비디오 객체에 현재 프레임 저장
        video.write(frame)
        # 녹화중이라는 것을 보여주기 위해 보여주는 화면에는 빨간색 점을 표시해줌
        cv2.circle(img=frame, center=(620, 15), radius=5, color=(0,0,255), thickness=-1)
        
    cv2.imshow("original", frame)   # frame(카메라 영상)을 original 이라는 창에 띄워줌 
    if cv2.waitKey(1) == ord('q'):  # 키보드의 q 를 누르면 무한루프가 멈춤
            break

In [ ]:
capture.release()                   # 캡처 객체를 없애줌
cv2.destroyAllWindows()             # 모든 영상 창을 닫아줌